apiVersion: v1
kind: Service
metadata:
  name: notifications-consumer-service
  namespace: etsi-mec-hackathon
spec:
  type: NodePort
  selector:
    app: notifications-consumer
  ports:
    - name: callbacks
      protocol: TCP
      port: 6100 
      targetPort: 6100
  externalIPs:
    - xxx.xxx.xxx.xxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-consumer 
  namespace: etsi-mec-hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-consumer
  template:
    metadata:
      labels:
        app: notifications-consumer
    spec:
      containers:
        - name: notifications-consumer
          image: notifications-consumer
          ports:
            - containerPort: 6100
              protocol: TCP
          imagePullPolicy: IfNotPresent
